runtime: php72 # Replace with php73 to use the PHP 7.3 runtime

handlers:
# Serve a directory as a static resource.
- url: /styles
  static_dir: styles
  
- url: /scripts
  static_dir: scripts

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: "mysql:unix_socket=/cloudsql/ssmm-safe-transportation:europe-west1:ssmm-transport-database;dbname=ssmm-database"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "vilarinyoputoamoenrobotica2020"