runtime: python37
env_variables:
#  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
# # values obtained when configuring your Cloud SQL instance.
  
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_DATABASE_NAME: ssmm_transport
  CLOUD_SQL_PASSWORD: ssmm2020
  CLOUD_SQL_CONNECTION_NAME: ssmm-transport-python:europe-west1:ssmm-transport-database
  MYSQL_USER: root
  MYSQL_PASSWORD: vilarinyoputoamoenrobotica2020