runtime: php72 # Replace with php73 to use the PHP 7.3 runtime

handlers:
# Serve a directory as a static resource.
- url: /styles
  static_dir: styles
  
- url: /scripts
  static_dir: scripts

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto